### ISSUE TITLE
Documentation: make it clearer about the node.js version to use

### ISSUE THREAD

**Issue by Kawacrepe** [replicate/replicate-javascript#100]
Hello guys :)

I got an issue while trying to work with the replicate library due to the fact I was running my project with node.js 16 **without** the [nodejs experimental flag](https://nodejs.org/api/globals.html#fetch:~:text=No%20longer%20behind-,%2D%2Dexperimental%2Dglobal%2Dfetch,-CLI%20flag.)

I think it should be cool to add something in the library documentation in order to explain it or maybe update the `engines` in the package.json to force the end user using node.js version > 18

I can create a PR in order to fix that :)

**Comment by mattt** [comment]
Hi @Kawacrepe. This is currently documented in the README, under the ["Constructor"](https://github.com/replicate/replicate-javascript#constructor) heading:

> The client makes requests to Replicate's API using [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch). By default, the globalThis.fetch function is used, which is available on [Node.js 18](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental) and later, as well as [Cloudflare Workers](https://developers.cloudflare.com/workers/runtime-apis/fetch/), [Vercel Edge Functions](https://vercel.com/docs/concepts/functions/edge-functions), and other environments.
>
> On earlier versions of Node.js and other environments where global fetch isn't available, you can install a fetch function from an external package like [cross-fetch](https://www.npmjs.com/package/cross-fetch) and pass it to the fetch option in the constructor.

Replicate should work on any supported version of Node provided that there's a `fetch` function available, so I'm not sure updating the `engines` for the package would be appropriate.

**Comment by JeffJassky** [comment]
When using yarn as a package manager, I can't get it to install on node 16.
```
error replicate@0.25.2: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.1"
warning replicate@0.25.2: The engine "git" appears to be invalid.
error Found incompatible module.
```

Unfortunately, my only real option is to fork the package and change the engines value to allow me to install it.
