### ISSUE TITLE
Broken TypeScript types in 0.14.0

### ISSUE THREAD

**Issue by thomasballinger** [replicate/replicate-javascript#109]
Hello! A user reported two TypeScript errors in 0.14.0 from syntax like `progress?: (Prediction) => void`. 
* https://github.com/replicate/replicate-javascript/blob/main/index.d.ts#L93
* https://github.com/replicate/replicate-javascript/blob/main/index.d.ts#L111

one of these was added here, sorry for the double-post:
https://github.com/replicate/replicate-javascript/commit/fbc3bf26b77b7356a56a74725e0bae974fb56c79#r123186503

I haven't repro'd this, so don't know if fixing these two is enough to fix.

**Comment by mattt** [comment]
Hi @thomasballinger. Thanks for reporting this. Apologies for the inconvenience.

I just opened https://github.com/replicate/replicate-javascript/pull/110. Does that look right to you?

**Comment by mattt** [comment]
This should now be fixed with [v0.14.1](https://github.com/replicate/replicate-javascript/releases/tag/v0.14.1).

**Comment by mattt** [comment]
I also just merged https://github.com/replicate/replicate-javascript/pull/113, which should prevent these kinds of problems from happening the future.

Thanks again for opening this issue, @thomasballinger!
