### ISSUE TITLE
Headers is not defined

### ISSUE THREAD

**Issue by tenonin** [replicate/replicate-javascript#116]
I tried to run the example code and give this error, but i don't know to fix

```
node index.js 
/mnt/c/Pitang/StableDiffusion/node_modules/replicate/index.js:189
const headers = new Headers();

ReferenceError: Headers is not defined
    at Replicate.request (/mnt/c/Pitang/StableDiffusion/node_modules/replicate/index.js:189:21)
    at Replicate.createPrediction (/mnt/c/Pitang/StableDiffusion/node_modules/replicate/lib/predictions.js:24:31)
    at Replicate.run (/mnt/c/Pitang/StableDiffusion/node_modules/replicate/index.js:116:45)
    at file:///mnt/c/Pitang/StableDiffusion/index.js:15:32
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)```

**Comment by mattt** [comment]
@tenonin What version of Node.js are you running?

**Comment by tenonin** [comment]
it's v16.17.0

**Comment by mattt** [comment]
@tenonin Thanks for clarifying. 

The Replicate client makes requests using [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch). By default, the `globalThis.fetch` function is used, which is available on [Node.js 18](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental) and later. From the [README](https://github.com/replicate/replicate-javascript#constructor):

> On earlier versions of Node.js
> and other environments where global fetch isn't available,
> you can install a fetch function from an external package like
> [cross-fetch](https://www.npmjs.com/package/cross-fetch)
> and pass it to the `fetch` option in the constructor.
> 
> ```js
> import Replicate from "replicate";
> import fetch from "cross-fetch";
> 
> const replicate = new Replicate({
>   // get your token from https://replicate.com/account
>   auth: process.env.REPLICATE_API_TOKEN,
>   fetch: fetch,
> });
> ```

**Comment by jasongrishkoff** [comment]
I've been encountering this same issue (on node 14). I pass `fetch` exactly as shown in the above comment, but it comes back saying Headers is not defined. I looked at the source code, and I do see it calls `new Headers()` [here](https://github.com/replicate/replicate-javascript/blob/b14eeaaf5e3a921ca372487103efbf5c52069c4d/index.js#L193). I think that should maybe reference `options.fetch` if that was defined, as in [this answer](https://stackoverflow.com/a/65766305)?

Rolling back to version `0.11.1` allowed me to run without any errors.
