### ISSUE TITLE
How does linting work in this project?

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-javascript#119]
When I make changes to the files in this project in VSCode, it makes a bunch of formatting changes that I end up having to revert. I don't care what settings we're using here, I just don't want my editor to trample on them.

This project uses eslint and editorconfig, and it has `.vscode/settings.json` file.

When I run `npm run lint` on the main branch, all is well.

When I open a file like `index.js` or `index.test.ts` in VSCode and hit Save, it formats a bunch of the code, leading to a huge diff. `npm run lint` still passes after those changes, so apparently eslint is indifferent about all those formatting preferences that my editor is applying on save?

Forgive my ignorance on the matter, but what am I doing wrong here?

**Comment by mattt** [comment]
> Forgive my ignorance on the matter, but what am I doing wrong here?

@zeke I've had this problem with pretty much every JS project I've touched — including this one, on occasion. Small configuration changes or invisible updates to some tool in my stack results in large, chaotic formatting diffs. I can't account for this, and it drives me nuts.

I don't particularly care for one convention over another. All I want is exactly what you describe: to open up the project in a fresh VSCode instance and have everything format and lint correctly.
