### ISSUE TITLE
Support process.env.REPLICATE_API_TOKEN for implicit auth?

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-javascript#121]
To use the client today, you have to do this:

```js
const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
});
```

What if you could just do:

```js
const replicate = new Replicate()
```

..and have it default to `process.env.REPLICATE_API_TOKEN`, if present?

This is similar to how the [Python client works](https://github.com/replicate/replicate-python#authenticate), and I kinda like it. Also makes code examples a lot cleaner.

**Comment by mattt** [comment]
I agree that the latter makes for better-looking sample code. But the implicit auth behavior in the Python client is among the most frequent points of confusion / friction from users. I think the Python koan of ["Explicit is better than implicit"](https://peps.python.org/pep-0020/) applies.

Not to say that we can't do better here!

What do you think about something like [what we did in the Go client](https://github.com/replicate/replicate-go/pull/6/files#diff-4b667feae66c9d46b21b9ecc19e8958cf4472d162ce0a47ac3e8386af8bbd8cfR78-R91)? Do you know of any good examples / conventions for JS client constructors that read from env like that?

**Comment by zeke** [comment]
>  the implicit auth behavior in the Python client is among the most frequent points of confusion / friction from users.

What makes it a point of friction? Is it because the client blows up weirdly if the token is missing? Or because you're forced to do auth that way?

I think what's different about what I'm proposing here is that you have the option: set the `auth` option explicitly, or implicitly fall back to the env var.

> What do you think about something like [what we did in the Go client](https://github.com/replicate/replicate-go/pull/6/files#diff-4b667feae66c9d46b21b9ecc19e8958cf4472d162ce0a47ac3e8386af8bbd8cfR78-R91)?

```go
client := replicate.NewClient(replicate.WithTokenFromEnv())
```

That could work, but might feel a bit unfamiliar. I can't recall ever seeing a pattern like that in JS land for loading from env.

**Comment by mattt** [comment]
@zeke You know, I'm starting to come around to this. Opened https://github.com/replicate/replicate-javascript/pull/127 with the change.
