### ISSUE TITLE
Headers is not defined

### ISSUE THREAD

**Issue by phnk-in** [replicate/replicate-javascript#124]
##### my code

```
const replicate = new Replicate({
      auth: process.env.REPLICATE_API_TOKEN,
    });
    const output = await replicate.run(
  "stability-ai/sdxl:a00d0b7dcbb9c3fbb34ba87d2d5b46c56969c84a628bf778a7fdaec30b1b99c5",
  {
    input: {
      prompt: "An astronaut riding a rainbow unicorn"
    }
  }
```

output always return Headers is not defined

**Comment by mattt** [comment]
@phnk-in What version of Node.js and the Replicate library are you using? That's the kind of error I'd expect to see if your environment didn't have the required `fetch` API.

**Comment by phnk-in** [comment]
I'm using latest two versions (0.16.0 and 0.16.1) but both have same issue

**Comment by greeeden** [comment]
In my case there was a problem due to node.js version v15.14.0, I switched to version 18.16.0 and everything worked.

**Comment by mattt** [comment]
@phnk-in I'm pretty sure your issue would be resolved by upgrading to a supported version of Node.js or pulling in a compatible polyfill for `fetch` (and `Headers`) as described in the README. Please let me know if that doesn't help, and I'd be happy to reopen.
