### ISSUE TITLE
How can I input an image into the API?

### ISSUE THREAD

**Issue by kenhuang1964** [replicate/replicate-javascript#125]
I noticed that the image input has to be in the io.IOBase type. I am currently using node js for the API but I'm not sure how to convert my data into that file type. I have the data's URI (not sure if this is useful). Thanks in advance!

**Comment by mattt** [comment]
Hi @kenhuang1964. If you already have the `data` URI, then you can pass it directly.

From the [README](https://github.com/replicate/replicate-javascript#usage):

> To run a model that takes a file input, convert its data into a base64-encoded data URI:

```js
import { promises as fs } from "fs";

// Read the file into a buffer
const data = await fs.readFile("path/to/image.png");
// Convert the buffer into a base64-encoded string
const base64 = data.toString("base64");
// Set MIME type for PNG image
const mimeType = "image/png";
// Create the data URI
const dataURI = `data:${mimeType};base64,${base64}`;

const model = "nightmareai/real-esrgan:42fed1c4974146d4d2414e2be2c5277c7fcf05fcc3a73abf41610695738c1d7b";
const input = {
  image: dataURI,
};
const output = await replicate.run(model, { input });
// ['https://replicate.delivery/mgxm/e7b0e122-9daa-410e-8cde-006c7308ff4d/output.png']
```

**Comment by kenhuang1964** [comment]
Thank you @mattt! That got it to work!
