### ISSUE TITLE
Bug: await replicate.run hangs forever

### ISSUE THREAD

**Issue by Rizean** [replicate/replicate-javascript#126]
In the example below if `shouldRun = true` then the code will hang forever on `output = await replicate.run`. If you kill the process and set `shouldRun = false` then the `replicate.predictions.list` will likely show the prediction as `succeeded`.

Edit: I just checked the dashboard and not only does it hang it seems to hang on the server side as well. The backend was stuck `starting` until I killed the process. As soon as I killed the process the dashboard switched to `running`

Edit2: This seems to be a specific problem with `lucataco/vicuna-33b-v1.3:373b7701a9993286eaa9b892277a81be71a1dd981d4f02da876d5864749f81ef` I tested the `replicate/vicuna-13b:6282abe6a492de4145d7bb601023762212f9ddbbe78278bd6771c8b3b2f2a13b` without issue.

Edit3: I passed bad data (model string) to `replicate.run` and it had the exact same behavior on the client side. No observable server-side effect. 

~~Also, just wondering why `vicuna-33b` doesn't support streaming?~~

```javascript
require("dotenv").config();
const Replicate =  require("replicate");

const replicate = new Replicate({
    auth: process.env.REPLICATE_API_TOKEN',
});

const prompt = `What is the meaning of life?.`

const shouldRun = true

const main = async () => {

    if (shouldRun) {
        const output = await replicate.run(
            "lucataco/vicuna-33b-v1.3:373b7701a9993286eaa9b892277a81be71a1dd981d4f02da876d5864749f81ef",
            {
                input: {
                    prompt,
                    max_new_tokens: 256
                }
            }
        );

        console.log(output);
    }

    const response = await replicate.predictions.list()
    console.log(response)
    
    response.results.map(async (prediction) => {
        if (prediction.status !== "succeeded") {
            return
        }
        await replicate.predictions.get(prediction.id)
            .then((predictionResult) => {
                console.log(prediction.id, predictionResult);
            })
            .catch((err) => {
                console.log(err)
            })
    })

};

main().catch(console.error);
```

**Comment by mattt** [comment]
Hi @Rizean. Sorry for not responding sooner. Are you still seeing this behavior with the latest version of the Replicate client library?

**Comment by zeke** [comment]
Closing for lack of response. @Rizean feel free to chime in if you're still experiencing issues.
