### ISSUE TITLE
Add `started_at` to `Prediction` for Typescript types

### ISSUE THREAD

**Issue by dnosk** [replicate/replicate-javascript#128]
started_at is in the documentation and in the webhook, but not in the Typescript definition for Prediction.

**Comment by mattt** [comment]
Thanks for reporting this, @dnosk. This will be fixed by https://github.com/replicate/replicate-javascript/pull/129.

**Comment by mattt** [comment]
@dnosk This is now fixed in [v0.17.0](https://github.com/replicate/replicate-javascript/releases/tag/v0.17.0)
