### ISSUE TITLE
Document how to use modules in your app

### ISSUE THREAD

**Issue by bfirsh** [replicate/replicate-javascript#130]
I saw somebody today stumble because they didn't have `"type": "module"` in their package.json.

Problem is the example isn't going to work if you have an existing project that doesn't use modules, so maybe we need to document how to use `require()` too.

**Comment by aron** [comment]
Documented in [91ff08b](https://github.com/replicate/replicate-javascript/commit/91ff08b3d0a23e23b51c533cecb519b2b5270875)
