### ISSUE TITLE
Private model not returning output

### ISSUE THREAD

**Issue by idarbuashvili** [replicate/replicate-javascript#146]
Hello, 

We fine-tuned the SDXL model into a private model on Replicate. After running prediction requests on it,
we are not getting any output from the model, `replicate` version is `v0.20.1`.

**Comment by mattt** [comment]
Hi @idarbuashvili. Could you please share the ID of a prediction that failed and the code you're using to run a model (redacting the model name)? Does the model produce output as expected when running it on the website?

**Comment by idarbuashvili** [comment]
Hi @mattt, sure, here `h6nr6qlb4bjkugqcd6oxwppeiy` is the prediction id. Here is the code:

```
const output = (await this.#replicate.run(
      predictionURL,
      {
        input: {
          image: `data:${imageMimeType};base64,${image}`,
          prompt,
          ...input,

          ...(this.#enableRefiner
            ? {
                refine: 'expert_ensemble_refiner', 

                // NOTE: If `refine` is `base_image_refiner`, give `refiner_steps`
                // refiner_steps: config.replicate.stableDiffusion.input['num_inference_steps'],
              }
            : {}),
        },
      },
      this.#progressCallback()
    ))
```

I am getting `prediction` in progressCallback, but logs part is always empty, it's not possible to detect progress of the model. Tried using `webhook` version with filters, but same result. Just in case, tried creating prediction using `predictions.create` as well, but to the same result.

**Comment by idarbuashvili** [comment]
It's an SDXL model, retrained using replicate on replicate servers, and saved to a private model.

**Comment by mattt** [comment]
Thanks for sharing that context, @idarbuashvili. I think there's an issue with logs not displaying for fine-tuned SDXL models. I'm looking into the current status of that.

The data for predictions created through the API are deleted after an hour, so I can't see any inputs / outputs or logs (if any). Could you try reproducing that through the web UI, which don't expire automatically?

**Comment by idarbuashvili** [comment]
Hm strange, just checked and both, call through `replicate-javascript` and through web ui work fine. Now I am getting logs in callback, maybe private models need some time to get fully available?

**Comment by mattt** [comment]
@idarbuashvili I'm so glad to hear that's working again for you. I discussed with a colleague, and it seems there we deployed a fix to logs for fine-tuned models earlier today. If you see this issue again, please let me know!

**Comment by idarbuashvili** [comment]
Thanks for help, and glad to hear fix got deployed

**Comment by mattt** [comment]
Will do! Let me know if there's anything else to do here, and I'd be happy reopen.
