### ISSUE TITLE
No custom headers (nor other sig) received by webhook

### ISSUE THREAD

**Issue by cureau** [replicate/replicate-javascript#149]
I've tried to add customer headers but they don't get received by the webhook. Which also makes me wonder how it's recommended to secure one's webhook since there doesn't seem to be any built-in signatures either.

## Environment

Node 18.16.0

## Fetch assignment

Note that fetch is being invoked despite no headers.

```
replicate.fetch = (url: string, options: any) => {
  console.log('Custom fetch invoked', url, options);

  const headers = new Headers(options && options.headers);
  headers.append('X-Shared-Secret', process.env.MY_SECRET || '');
  return fetch(url, { ...options, headers });
};
```

## Example webhook body

**Issue is there is no req.headers['X-Shared-Secret'];**

```
  'cache-control': '',
  'x-forwarded-host': 'tunnel.example.com',
  'x-forwarded-port': '80',
  'x-forwarded-proto': 'https,http',
  'x-forwarded-for': '35.239.10.115,::1',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '1178',
  'user-agent': 'replicate-webhook/82463df',
  host: 'tunnel.example.com',
  date: 'Sun, 22 Oct 2023 02:45:57 GMT',
  'x-middleware-next': '1',
  'x-middleware-invoke': '',
  'x-invoke-path': '/api/replicate/receive/transcript',
  'x-invoke-query': '%7B%22id%22%3A%222491%22%7D',
  connection: 'close'
}
```

**Comment by mattt** [comment]
Hi @cureau. By customizing the `fetch` function in the JavaScript client, you can set custom headers in requests sent to Replicate's API. However, at the moment, any headers other than `Authentication` are effectively ignored by the API.

Replicate's API doesn't currently support webhook secrets or signatures. But you can pass a query parameter to the webhook URL and use that to similar effect. From ["Using webhooks"](https://replicate.com/docs/webhooks) on Replicate's website:

> ### Tips
>
> Add query params to your webhook URL to pass along extra metadata, like an internal ID you’re using for a prediction. For example https://example.com/replicate-webhook?customId=123

**Comment by cureau** [comment]
Thank you @mattt  ... that's what we're doing now. It seems like a security risk with referer headers, logs, etc. But I suppose that's up to Replicate.

Appreciate the help

**Comment by mattt** [comment]
@cureau I'm with you about webhook security. This is something I'd like to improve in Replicate, so I appreciate your mentioning it here. Though if I have a chance to work on this, I'd likely implement [HMAC](https://webhooks.fyi/security/hmac) instead of a shared secret.
