### ISSUE TITLE
Node.js SDK and service questions

### ISSUE THREAD

**Issue by dabit3** [replicate/replicate-javascript#150]
I have a couple of questions that I'll bundle here since they all come from a specific use case, building with the Node.js streaming SDK:

1. I'm noticing there is a timeout error after about 25-35 seconds when making a long running stream request to the API / service if it has not yet processed. Is there a way to configure a longer timeout here, or maybe this is an error / issue that should not be happening?

Using https://replicate.com/yorickvp/llava-13b

Code:

```
  let prediction = await replicate.deployments.predictions.create(
    "dabit3",
    "aibuddy-llava",
    {
      input: {
        image: dataURI,
        prompt
      },
      stream: true
    }
 )

  prediction = await replicate.wait(prediction);

  if (prediction && prediction.urls && prediction.urls.stream) {
    const source = new EventSource(prediction.urls.stream, { withCredentials: true });
    source.addEventListener("output", (e) => {
      console.log("output", e)
      res.write(`data: ${JSON.stringify(e)}\n\n`)
    });
  
    source.addEventListener("error", (e) => {
      // this gets called ~30 seconds if there is no response
      console.log('error in event listener:', e)
      res.write('data: [DONE]\n\n')
      source.close()
      res.end()
    });
  
    source.addEventListener("done", (e) => {
      console.log("done", e)
      res.write('data: [DONE]\n\n')
      source.close()
      res.end()
    })
  }
```
    
2. Deployments sometimes taking an hour to start, still unsure if they will finish booting up, Is this normal?

<img width="1179" alt="Screenshot 2023-10-26 at 10 23 33 PM" src="https://github.com/replicate/replicate-javascript/assets/1857282/b04b794a-2213-4f52-b57a-0365a9ada1f8">

**Comment by mattt** [comment]
Hi @dabit3. In the first case, the long timeout may have to do with the data URI sent in the request body. If you're sending a large image, try uploading that to a publicly accessible URL and passing that URL instead.

As for your deployment, something looks wrong there. I've shared this with our infra team, and will investigate further.

**Comment by dabit3** [comment]
oh wow, both of those suggestions worked like a charm, thanks for your prompt response!

**Comment by mattt** [comment]
@dabit3 I totally agree. A files API is something we've been discussing internally. No timeline or specific plans to share at the moment, but I'm hoping we can have a better solution for file management soon.
