### ISSUE TITLE
Calling replicate image generation in parallel not working

### ISSUE THREAD

**Issue by jaukia** [replicate/replicate-javascript#156]
I'm having issues calling Replicate run in parallel from node.js. I call replicate.run three times and then wait for all of the Promises to finish with Promise.all.

What I see happening is that replicate.run is called three times, but only one of the runs progresses at a time. When the first one finishes, the next continues, and so on.

What I'd expect to see is the three runs to run concurrently and finish roughly simultaneously.

Is this an issue related to the default fetch implementation, the node.js replicate client, the HTTP replicate API, or something else?

Log updates look like this for the three runs:

[dev] ## starting replicate run 0
[dev] ## run 0 started
[dev] ## starting replicate run 1
[dev] ## run 1 started
[dev] ## starting replicate run 2
[dev] ## run 2 started
[dev] Progress for 0: 20%
[dev] Progress for 0: 80%
[dev] Progress for 0: 80%
[dev] Progress for 0: 80%
[dev] Progress for 0: 100%
[dev] Progress for 1: 20%
[dev] Progress for 1: 20%
[dev] Progress for 1: 80%
[dev] Progress for 1: 80%
[dev] Progress for 1: 100%
[dev] Progress for 2: 20%
[dev] Progress for 2: 20%
[dev] Progress for 2: 80%
[dev] Progress for 2: 80%
[dev] Progress for 2: 100%

**Comment by mattt** [comment]
Hi @jaukia. Can you share example code that demonstrates this behavior?

**Comment by jaukia** [comment]
Sure, I'll try to make a stand-alone example to demonstrate this.

**Comment by davidarice** [comment]
I'm seeing the same thing:

```js
import Replicate from "replicate";

const replicate = new Replicate({
  auth: "REPLICATE_API_KEY",
});

// the promise collection
let promises = [];

// run it 10x
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].forEach(async (num) => {
  const model = "stability-ai/stable-diffusion:af1a68a271597604546c09c64aabcd7782c114a63539a4a8d14d1eeda5630c33";
  const input = {
    prompt: `${num} cats wearing ${num} hats`,
  };
  promises.push(await replicate.run(model, { input }));
});

await Promise.all(promises);
```

In the Dashboard, the reported status is Starting for all, then Running for one at a time:
<img width="1494" alt="Screenshot 2023-11-08 at 9 07 23 PM" src="https://github.com/replicate/replicate-javascript/assets/53280803/0c1fcf4f-8e8c-492d-8c48-df156c96c855">
<img width="1486" alt="Screenshot 2023-11-08 at 9 07 31 PM" src="https://github.com/replicate/replicate-javascript/assets/53280803/a27de79a-709e-4ed5-b500-92738a73a62c">

**Comment by jaukia** [comment]
Here is a simplified stand-alone example code to produce the issue:

```
import Replicate, { Prediction } from 'replicate';
import { IllustrationData } from '~/types/brandTypes';

const runProgress = (index: number, prediction: Prediction) => {
    const logLines = prediction.logs?.split('\n');
    const percentageLine = logLines?.reverse().find(line => line.includes('%'));
    if (percentageLine) {
        const percentageMatch = percentageLine.match(/(\d+)%/);
        if (percentageMatch) {
            console.log('Progress for ' + index + ": " + percentageMatch[1] + "%");
            return parseInt(percentageMatch[1], 10);
        }

    }
    return undefined;
};

const generateIllustration = async (promptText: string, index: number, illustrationStatus: IllustrationData[]) => {

    if (!process.env.REPLICATE_API_TOKEN) {
        console.error('replicate api token not set');
        return;
    }

    try {
        const replicate = new Replicate({
            auth: process.env.REPLICATE_API_TOKEN,
        });

        console.log("## starting replicate run", index);
        return (replicate.run(
            "lucataco/ssd-1b:1ee85ef681d5ad3d6870b9da1a4543cb3ad702d036fa5b5210f133b83b05a780",
            {
                input: {
                    prompt: promptText,
                    width: 640,
                    height: 1024,
                    num_inference_steps: 30,
                    guidance_scale: 28,
                    negative_prompt: "text, amateur, writing, screenshot, mockup, blurry, unsharp, intricate, complex"
                },
            },
            (prediction: Prediction) => {
                const progress = runProgress(index, prediction);
                illustrationStatus[index].progress = progress;
            }
        ));

    } catch (error) {
        console.error('### ERROR — ', error);
    }

};

const testReplicate = () => {

    try {

        const illustrationStatus: IllustrationData[] = [
            {
                prompt: "",
                url: undefined,
                progress: undefined,
            },
            {
                prompt: "",
                url: undefined,
                progress: undefined,
            },
            {
                prompt: "",
                url: undefined,
                progress: undefined,
            }
        ];

        const bindIllustrationGeneration = (state: IllustrationData, index: number) => {
            return generateIllustration(state.prompt, index, illustrationStatus).then((output: any) => {
                illustrationStatus[index].url = (output as string[])[0];
            });
        };

        let illustrationPromises = [undefined, undefined, undefined] as (Promise<any> | undefined)[];

        illustrationPromises[0] = bindIllustrationGeneration(illustrationStatus[0], 0);
        console.log("## illustration 1 started");

        illustrationPromises[1] = bindIllustrationGeneration(illustrationStatus[1], 1);
        console.log("## illustration 2 started");

        illustrationPromises[2] = bindIllustrationGeneration(illustrationStatus[2], 2);
        console.log("## illustration 3 started");

        Promise.all(illustrationPromises).then(() => {
            console.log('All illustrations created');
        }).catch((error) => {
            console.error('Error creating illustrations:', error);
        });

    } catch (e) {
        console.error(e);
    }
};

testReplicate();
```

Log

```
## starting replicate run 0
## illustration 1 started
## starting replicate run 1
## illustration 2 started
## starting replicate run 2
## illustration 3 started
Progress for 1: 20%
Progress for 1: 53%
Progress for 1: 87%
Progress for 1: 87%
Progress for 1: 100%
Progress for 0: 20%
Progress for 0: 53%
Progress for 0: 87%
Progress for 0: 87%
Progress for 0: 100%
Progress for 2: 20%
Progress for 2: 53%
Progress for 2: 87%
Progress for 2: 87%
Progress for 2: 100%
All illustrations created
```

**Comment by mattt** [comment]
@davidarice Thanks for sharing that code. I may be reading your code wrong, but it looks like `promises.push(await replicate.run(model, { input }))` is waiting for the result and pushing the resolved result. What happens if you remove the leading `await`?

**Comment by davidarice** [comment]
Ahh! Whoops! That seems to do the trick, I can see all processes running at the same time now!

**Comment by mattt** [comment]
@davidarice So glad to hear you got it working!

@jaukia I'm having more trouble understanding the code sample you posted. It appears to be generating promises correctly, but it's not obvious what's wrong. `generateIllustration` shouldn't be async, but I don't think that's it.

Does anything from @davidarice's example help you solve this?

**Comment by davidarice** [comment]
Interesting to note, Matt, is that there is a difference when the model name is changes from 'stable-diffusion' to 'sdxl':

```js
const model = "stability-ai/stable-diffusion:af1a68a271597604546c09c64aabcd7782c114a63539a4a8d14d1eeda5630c33";
const model = "stability-ai/sdxl:af1a68a271597604546c09c64aabcd7782c114a63539a4a8d14d1eeda5630c33";
```

'stable-diffusion' works in parallel, but 'sdxl' does not.

**Comment by mattt** [comment]
@davidarice FWIW, the model names aren't interchangeable. The identifier `af1a68a271597604546c09c64aabcd7782c114a63539a4a8d14d1eeda5630c33` corresponds to [a specific version of SDXL](https://replicate.com/stability-ai/sdxl/versions/af1a68a271597604546c09c64aabcd7782c114a63539a4a8d14d1eeda5630c33). For now, the model name isn't checked, but this may change in the future. 

`af1a68a` is not a popular version of SDXL. Based on what I can see about its performance, I think what's happening is that the prediction requests are being queued. Without having or inducing additional demand or time to scale more nodes, your requests have the effect of running serially on that single instance. If you change to a more popular version with existing capacity, like `39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b`, I suspect your predictions would execute in parallel.

**Comment by davidarice** [comment]
Yup, you're absolutely right. I've been fighting that this whole time and just realized my mistake....Thanks. 

Good luck to @jaukia, hopefully they get their issue resolved!

**Comment by jaukia** [comment]
Ah, I see, that explains it. I'll try out a more popular model to see if the performance is better, thanks!
