### ISSUE TITLE
Fix or explain use of modules with TypeScript

### ISSUE THREAD

**Issue by mattt** [replicate/replicate-javascript#162]
In https://github.com/replicate/replicate-javascript/issues/161#issuecomment-1816333059, a user reported the following error:

> `TypeError: replicate_1.default is not a constructor`

A solution was to add `"esModuleInterop": true` to the project's `tsconfig.json` file.

We should either make this step unnecessary, or barring that, document this workaround.

**Comment by depyronick** [comment]
Note that if you are going to use `esModuleInterop`, you probably won't be able to use `* as Module` imports anymore.

**Comment by zeke** [comment]
Is this still relevant? cc @aron
