### ISSUE TITLE
[Bug]: _fetch is not a function

### ISSUE THREAD

**Issue by SleeplessOne1917** [replicate/replicate-javascript#175]
Sorry to be opening another issue again so soon, but I ran into another bug. Here are the logs I got:

```
Dec 19 15:31:24 lemmygrad-art-bot pnpm[1070]: TypeError: _fetch is not a function
Dec 19 15:31:24 lemmygrad-art-bot pnpm[1070]:     at withAutomaticRetries.shouldRetry.shouldRetry (/home/insomnia/lemmy-art-bot/node_modules/.pnpm/replicate@0.25.2/node_modules/replicate/index.js:220:61)
Dec 19 15:31:24 lemmygrad-art-bot pnpm[1070]:     at withAutomaticRetries (/home/insomnia/lemmy-art-bot/node_modules/.pnpm/replicate@0.25.2/node_modules/replicate/lib/util.js:68:10)
Dec 19 15:31:24 lemmygrad-art-bot pnpm[1070]:     at async Replicate.request (/home/insomnia/lemmy-art-bot/node_modules/.pnpm/replicate@0.25.2/node_modules/replicate/index.js:220:22)
Dec 19 15:31:24 lemmygrad-art-bot pnpm[1070]:     at async Replicate.createPrediction (/home/insomnia/lemmy-art-bot/node_modules/.pnpm/replicate@0.25.2/node_modules/replicate/lib/predictions.js:27:16)
Dec 19 15:31:24 lemmygrad-art-bot pnpm[1070]:     at async Replicate.run (/home/insomnia/lemmy-art-bot/node_modules/.pnpm/replicate@0.25.2/node_modules/replicate/index.js:113:20)
```

I'm not overriding the `fetch` replicate uses. This is what my newing up of the `Replicate` class looks like:

```typescript
const replicate = new Replicate({
  auth: API_KEY,
});
```

As before, I am running on Node version 20.10.0, so global fetch should be defined.

**Comment by mattt** [comment]
@SleeplessOne1917 Not at all — thanks for reporting this.

As you said, Node.js 20 should have built-in native `fetch`. Just to make sure, can you share the output of `node --version` for your project? Also, I'm curious to see what your project logs for `globalThis.fetch`.

**Comment by mattt** [comment]
Looking at [this line](https://github.com/SleeplessOne1917/lemmy-art-bot/blob/99968a9a9911272b877acc40404cd52a265f8706/package.json#L14), it looks like you're installing the type definitions for Node.js 20. But your project may be using an older version. The way to enforce a project's Node.js requirement is to set the `engines` key in `package.json`:

```
"engines": {
    "node": ">=18.0.0"
}
```

**Comment by SleeplessOne1917** [comment]
Node version:

```
[insomnia@lemmygrad-art-bot lemmy-art-bot]$ node --version
v20.10.0
```

Logging `globalThis.fetch`:

```typescript
[Function: fetch]
```

> On [this line](https://github.com/SleeplessOne1917/lemmy-art-bot/blob/99968a9a9911272b877acc40404cd52a265f8706/package.json#L14), it looks like you're installing the type definitions for Node.js 20. But your project may be using an older version. The way to enforce a project's Node.js requirement is to set the engines key in package.json

I will try that, although I don't know how it's possible for the project to be using an older version.

**Comment by mattt** [comment]
@SleeplessOne1917 Are you running [`npm start`](https://github.com/SleeplessOne1917/lemmy-art-bot/blob/99968a9a9911272b877acc40404cd52a265f8706/package.json#L8C15-L8C22)? That's using `ts-node`. I'm not sure what relation that has with the `node` command.

**Comment by SleeplessOne1917** [comment]
> Are you running [npm start](https://github.com/SleeplessOne1917/lemmy-art-bot/blob/99968a9a9911272b877acc40404cd52a265f8706/package.json#L8C15-L8C22)?

Yes, although I am using `pnpm` instead.

> That's using ts-node. I'm not sure what relation that has with the node command...

[From the package description](https://www.npmjs.com/package/ts-node): 

ts-node is a TypeScript execution engine and REPL for Node.js.

It JIT transforms TypeScript into JavaScript, enabling you to directly execute TypeScript on Node.js without precompiling. This is accomplished by hooking node's module loading APIs, enabling it to be used seamlessly alongside other Node.js tools and libraries.

> try running node --no-warnings --enable-source-maps --loader ts-node/esm bot.ts instead

That did not work.
```
[insomnia@lemmygrad-art-bot lemmy-art-bot]$ node --no-warnings --enable-source-maps --loader ts-node/esm bot.ts
/home/insomnia/lemmy-art-bot/bot.ts:1
import LemmyBot from 'lemmy-bot';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)

Node.js v20.10.0
```

**Comment by mattt** [comment]
@SleeplessOne1917 For that error, try adding `"type": "module"` to your `package.json`.

**Comment by SleeplessOne1917** [comment]
@mattt  That didn't fix it unfortunately. I tried it with both ts-node and the node command you suggested earlier.

**Comment by SleeplessOne1917** [comment]
I tried this on a different machine running the exact same node version and it worked. This one is a mystery for me. Closing because I can't reproduce the issue elsewhere.
