### ISSUE TITLE
Replicate Error: not found.

### ISSUE THREAD

**Issue by beatsea20** [replicate/replicate-javascript#180]
I am trying to use the Stable Diffusion model but there's replicate error: 'not found', even after setting my replicate api token.
`import os
import replicate
os.environ["REPLICATE_API_TOKEN"] = "mytoken"
api = replicate.Client(api_token=os.environ["REPLICATE_API_TOKEN"])`

`output = api.run(
    "sdxl-panorama/sha256:fd1f53277a424000168dfceeef58934c43bb3c27a3843a75e7b6d72c46cfc8fa",
    input={"prompt": "a prompt"}
)`

**Comment by mattt** [comment]
Hi @beatsea20. Replicate models are identified by username and name. Try using the identifier `"jbilcke/sdxl-panorama:fd1f53277a424000168dfceeef58934c43bb3c27a3843a75e7b6d72c46cfc8fa"`. Instructions for how to run the model can be found [on the API tab](https://replicate.com/jbilcke/sdxl-panorama/api?tab=nodejs) of model pages.
