### ISSUE TITLE
How to use this as require ( without ES6 )

### ISSUE THREAD

**Issue by aisummoner** [replicate/replicate-javascript#187]
const Replicate = require('replicate/index');

const replicate = new Replicate({
    auth: "xxxxxx",
});

**Comment by aron** [comment]
```js
const Replicate = require('replicate');

const replicate = new Replicate({
  auth: "xxxxxx",
});
```

There is now an example in the codebase:

https://github.com/replicate/replicate-javascript/blob/main/integration/commonjs/index.js
