### ISSUE TITLE
 Issue with Unauthorized Error on Follow-up Request in Model Training API

### ISSUE THREAD

**Issue by sambowenhughes** [replicate/replicate-javascript#194]
Hey

I'm currently working on a project using Next.js 14 and I've encountered a peculiar issue with your API that I hope you can help me with. My goal is to initiate model training through your API, and I've been following the prescribed method as per your documentation.

**Issue Summary**:
- I make a POST request to the API for model training. This request seemingly succeeds, returning a status code of 200, along with a JSON response containing various details such as the training ID, model info, and URLs for further actions (like 'get' and 'cancel').
- However, when I attempt to access the provided 'get' URL, I encounter a `401 Unauthorized` error with the message: "You did not pass an authentication token". This is unexpected since the initial POST request was authenticated and successful.

**Request Details** 
- **POST URL**: 'https://api.replicate.com/v1/models/stability-ai/sdxl/versions/da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf/trainings'
- **Request Body**: Includes `destination`, `source`, and `input_images` parameters.
- **Headers**: Include 'Content-Type: application/json' and 'Authorization: Token [Redacted]'.

**Successful POST Response Example**:
```json
{
  "id": "[Training ID]",
  "model": "stability-ai/sdxl",
  "version": "[Version ID]",
  "input": null,
  "logs": "",
  "error": null,
  "status": "starting",
  "created_at": "[Timestamp]",
  "urls": {
    "cancel": "[Cancel URL]",
    "get": "[Get URL]"
  }
}
```

**Error on Follow-up 'Get' Request**:
- **URL Accessed**: [Get URL from the Response]
- **Error Message**: `{"title":"Unauthenticated","detail":"You did not pass an authentication token","status":401}`

**Additional Context**:
- The same API call works as expected when executed via the CLI command.
- CLI Command: `replicate train --destination [Destination] --web stability-ai/sdxl input_images=[Image URL]`.

Given that the initial POST request is successful, it's unclear why the follow-up 'get' request is failing with an authentication error. Is there a step I'm missing, or is this an issue on the API's end? Any guidance or insights you can provide would be greatly appreciated.

**Comment by mattt** [comment]
@sambowenhughes Closing this for now. Happy to reopen if you still need help.
