### ISSUE TITLE
Path to v1.0

### ISSUE THREAD

**Issue by gr2m** [replicate/replicate-javascript#2]
- Unless you have strong reasons to use `.ts` files, I’d recommend to use `.js` + `.d.ts` to have full control over types and source code. I found that it saves a lot of head aches for libraries that are used by other people
    
    Here is how I would approach the implementation of the JS SDK
    
- I’d start out by implementing `replicate.request(route, parameters)` and its types. It’s the core piece, all other API methods will build upon it. This is the DX we are aiming for ([typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgeQMYwga2PAvnAMyghDgCIABCdLHAWgDsBTADxgHpVomyAoUSLHJUa2GI1YcYATzBMAznSgLxAQzDA+vLg3nxqGMXAC8cZgHcUonAAoAlL17t2cMMvny46KABs4Aajh5MFVUJjgAIyYYcyYmBjgYAAtwgEcAVwhVGAVeA1oYADplDJUbMjI7IA))
    
    ![screenshot](https://user-images.githubusercontent.com/39992/217392794-ae1f01c2-9abd-4130-9c82-5e6940b9237c.png)
    
    - In order to turn the generated OpenAPI types from `@replicate/openapi-types` into a map of `{ "GET /v1/collections/{collection_slug}": { /* parameters */ }, ...}` you can use the [Operation generic type from the upcoming Octokit](https://github.com/octokit/octokit-next.js/blob/main/packages/types-rest-api/operation.d.ts). That will allow us to build types [like this](https://github.com/octokit/octokit-next.js/blob/main/packages/types-rest-api/index.d.ts). We can generate this in future but for now I’d just write it out by hand, there are only a few endpoints anyway right now.
    - A reference implementation of the `request` method is here: [https://github.com/octokit/octokit-next.js/tree/main/packages/request](https://github.com/octokit/octokit-next.js/tree/main/packages/request)
    - Octokit publishes the request method standalone, but I think that’s overkill for replicate right now. I’d build it as part of the initial replicate API client, similar to Octokit’s `core` package: [https://github.com/octokit/octokit-next.js/tree/main/packages/core](https://github.com/octokit/octokit-next.js/tree/main/packages/core). Ignore the `withDefaults` and `withPlugins` class methods for now, they make things only complicated. Also ignore all the authentication strategy code, replicate only has token authentiation right now.
- Once the `replicate.request()` method is fully working, including authentication and types for all known routes, implement the REST API methods for all operations specified in the OpenAPI spec. Again this can be generated in future, but I’d probably just type it out as a first step.
- Then implement the `replicate.paginate()` method.  Prior art: https://github.com/octokit/plugin-paginate-rest.js/
- Finally implement the `replicate.createAndAwaitPrediction()` method.
- For http mocking in tests, make the `Replicate` constructor accept a `fetch` option, then defaults to the system `fetch`. In tests it can be set to [fetch-mock](https://github.com/wheresrhys/fetch-mock) instance instead ([example](https://github.com/octokit/octokit-next.js/blob/main/packages/core/test/request.test.js))
- For Type testing, use [tsd](https://github.com/SamVerschueren/tsd). ([example](https://github.com/octokit/octokit-next.js/blob/main/packages/request/index.test-d.ts))

**Comment by zeke** [comment]
@erbridge @gr2m it would be good to evaluate where we are on this path in our next call.

**Comment by mattt** [comment]
Thanks for all of your help and guidance with this project, @gr2m. What we have now as of [v0.9.0](https://github.com/replicate/replicate-javascript/releases/tag/v0.9.0) checks all of the functional boxes you laid out here.

For now, with only a handful of endpoints and a single authentication scheme to support, we can afford to define endpoints by hand. In the future, translating our OpenAPI spec with TypeScript type definitions looks like a good strategy for dealing with a larger API surface area.

There may be a few more things we'll want to do before a proper 1.0 release, but I think we can mark this issue as completed.
