### ISSUE TITLE
Reading from "node:crypto" is not handled by plugins

### ISSUE THREAD

**Issue by vishalvibes** [replicate/replicate-javascript#225]
### Environment:

**Node Version:** 20.11.1
**macOS:** 14.2.1
**next:** 14.1.3
**replicate:** 0.28.1

I am getting `Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).` while building my project.

`pnpm build` command is causing the issue but `pnpm dev` (developer mode) works fine.

<img width="816" alt="Screenshot 2024-03-18 at 12 30 44 PM" src="https://github.com/replicate/replicate-javascript/assets/29145212/bc221c5c-b81c-441c-ac4d-012b37e46e70">

**Comment by aron** [comment]
Googling your error message, this looks like a known issue with webpack.

https://github.com/webpack/webpack/issues/14798

the fix appears to be telling webpack about this using [externals](https://webpack.js.org/configuration/externals/).

```
module.exports = {
   externals: {
       'node:crypto': 'commonjs crypto'
   }
}
```

**Comment by bigOK666** [comment]
Any updates? I tried the `external` approach but the problem is not solved. I also tried the config mentioned in https://developer.tbd.website/docs/web5/troubleshooting/common-errors/ . It didn't work either.

My env:
Nextjs: 14.1.4
node: 20.5.0
replicate: 0.29.1

**Comment by bigOK666** [comment]
I guess the replicate package is not for interacting with Replicate API in browser. So I need to use HTTP API.

https://www.npmjs.com/package/replicate

**Comment by lucasishuman** [comment]
FWIW ~ I'm seeing the same error.

I am using Turborepo for a few web apps, all Next.js projects.

I am using this Replicate client + the Vercel AI SDK.

It was working OK until v0.2.7 when I started seeing the 'node:crypto' plugin error when trying to build my project. (same for all subsequent versions of replicate)

I tried some workarounds but haven't solved it yet...

**Comment by bigOK666** [comment]
@lucasishuman which package is v0.2.7? I am considering downgrade Replicate client.

**Comment by lucasishuman** [comment]
> @lucasishuman which package is v0.2.7?

Sorry, I mistyped the Replicate version...

Replicate v0.26.0 currently runs and builds fine for me so am I am using that for now.

Replicate v0.27.0+ will not build and shows the `UnhandledSchemeError: Reading from "node:crypto" ...` error.

**Comment by himself65** [comment]
Related: https://github.com/replicate/replicate-javascript/issues/210

**Comment by leonardofaria** [comment]
Using Next 14.4.2 and PNPM here. Solved here by editing the `next.config.js` and tweaking the webpack config:

```js
  webpack: (config) => {
    config.externals.push({
      'node:crypto': 'commonjs crypto',
    });
    return config;
  },
```

**Comment by lucasishuman** [comment]
@leonardofaria  - that worked for me, thanks.

**Comment by lucasishuman** [comment]
Although... this did _not_ work once deployed to my production environment (on Vercel)

```
Error: The Edge Function "src/middleware" is referencing unsupported modules:
	- __vc__ns__/1/index.js: crypto
```

So back to v0.26.0 for now...

**Comment by himself65** [comment]
> Although... this did _not_ work once deployed to my production environment (on Vercel)
> 
> ```
> Error: The Edge Function "src/middleware" is referencing unsupported modules:
> 	- __vc__ns__/1/index.js: crypto
> ```
> 
> So back to v0.26.0 for now...

What's the nodejs version you are setting? I should be 18, or better 20

**Comment by lucasishuman** [comment]
Node 18.18.2 locally - Replicate 0.29.1 + webpack externals config = ok

Node 18.x on Vercel (vercel screen grab below) - Replicate 0.29.1 + webpack externals config = error on build

![image](https://github.com/replicate/replicate-javascript/assets/1753761/09c9c708-3fe1-4e0a-81a7-35f2eeaee63e)

**Comment by himself65** [comment]
I just removed the `require('node:crypto')` code (PR: https://github.com/replicate/replicate-javascript/pull/243) and built a custom package, and pasted it into my codespace, and it seems to work

Here you can see how I made it: https://github.com/run-llama/LlamaIndexTS/pull/731/files#diff-0a946a42f586de9c04be9cfe31eec6a8ff9d14721b79565958dd13458ab9260e

**Comment by mattt** [comment]
Hey everyone. We just released [v0.29.3](https://github.com/replicate/replicate-javascript/releases/tag/v0.29.3), which includes changes from #250 that _should_ resolve things. Please let us know if they don't. Thanks for your patience and help finding a solution 🙇

**Comment by lucasishuman** [comment]
Looks good locally as well as deployed on Vercel using Node 18.x - thanks a ton!

**Comment by darshankalburgi** [comment]
> Using Next 14.4.2 and PNPM here. Solved here by editing the `next.config.js` and tweaking the webpack config:
> 
> ```js
>   webpack: (config) => {
>     config.externals.push({
>       'node:crypto': 'commonjs crypto',
>     });
>     return config;
>   },
> ```

Atleast it worked for now
