### ISSUE TITLE
Cannot seem to run mistral as it doesn't have a version

### ISSUE THREAD

**Issue by fraserburch** [replicate/replicate-javascript#245]
<img width="1009" alt="Screenshot 2024-04-22 at 9 22 18 PM" src="https://github.com/replicate/replicate-javascript/assets/25938517/e5e115c6-2f6d-4e7a-831a-3d704565271a">

Seems format in docs is:   `"stability-ai/sdxl:39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b"` 
What about for mistral: [This](https://replicate.com/mistralai/mistral-7b-instruct-v0.2/examples?input=nodejs) isn't working for me

**Comment by mattt** [comment]
@fraserburch What version of the Replicate library are you using? The type definitions for these functions have supported model identifiers with and without versions since #169.

https://github.com/replicate/replicate-javascript/blob/e42aa29f26494316e47d6ea9812f1fc760bd1021/index.d.ts#L129-L149

**Comment by fraserburch** [comment]
Maybe I'll manually make the change in the `index.d.ts` file! 
My version is definitely outdated, and I haven't had any luck updating it due to dependency conflicts! 

Thanks for the code snippet. Will give this a go!

**Comment by mattt** [comment]
> Maybe I'll manually make the change in the `index.d.ts` file!

Sounds good! Let me know how that works for you.

> My version is definitely outdated, and I haven't had any luck updating it due to dependency conflicts!

I'm curious to dig into this a bit more. Replicate has only a single optional dependency, and that's a recent addition. 

https://github.com/replicate/replicate-javascript/blob/main/package.json#L36-L48

Can you say more about how you've tried to upgrade and what errors you found? Like, what happens if you run `npm i replicate@latest`?

**Comment by fraserburch** [comment]
Hey Matt, We managed to update replicate module and resolve the conflicts. It wasn't replicate causing the conflicts, it was another module using replicate that was giving us grief! 

I'll close this ticket, but just one unrelated question. If I'm interacting with the rest api, is there anyway around the call to create prediction and then separate call to get the results? would be nice to just make one call and get back the result. Thanks!

**Comment by aron** [comment]
@fraserburch we don't have a "synchronous" api at the moment, but we are working on it.
