### ISSUE TITLE
Unexpected behavior: Error: Invalid version for official models

### ISSUE THREAD

**Issue by carafelix** [replicate/replicate-javascript#258]
Just following the api docs for running an api call for llama-3 outputs: 
```Invalid version. It must be in the format "owner/name:version"```
example copied from the model api reference tab:
```ts
const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN
});
const input = {
  prompt: 'Can you write a poem about open source machine learning?',
};
const output = await replicate.run("meta/meta-llama-3-8b", { input });
```
It's obviously not following the :version flag, but copypasting something from one of the first things you see in the API reference tab should work...
also the api response for getting the llama 3 8b is:
```json
{"status":404,"title":"Not found","detail":"This model is an official model and does not expose a list of versions."}
```

**Comment by aron** [comment]
Hi, sorry to hear you're having issues with the API. 

> Just following the api docs for running an api call for llama-3 outputs:
Invalid version. It must be in the format "owner/name:version"
example copied from the model api reference tab:

I've just copy/pasted your snippet and run it locally and things are working for me.

Can you share more about the version of `replicate` you have installed?

> also the api response for getting the llama 3 8b is…

Thanks, this is a bug in our SDK that we'll get fixed. In the mean time you can still access the model metadata via the HTTP endpoint.

The endpoint for fetching the model is:

    https://api.replicate.com/v1/models/meta/llama-3-8b

```
console.log(
  await fetch("https://api.replicate.com/v1/models/meta/llama-3-8b", {
    headers: { Authorization: `Bearer ${process.env.REPLICATE_API_TOKEN}` },
  }).then((r) => r.json()),
);

```

**Comment by carafelix** [comment]
>Can you share more about the version of replicate you have installed? 

replicate@0.18.1. Looks like ```npm i replicate``` is sourcing me an old version of the package. It becomes clear as surfing trough the index.js code its clearly different from the repo. Looks like the regex check was before an issue and in the update one is not.  
```npm i replicate@latest``` and it's okay
