### ISSUE TITLE
Possible to get access to prompts and answers from other users

### ISSUE THREAD

**Issue by Alkons** [replicate/replicate-javascript#262]
Following code returns logs in the response with previous runs from other users:

```
const client = new Replicate({
        auth: token
      });
const modelData = await client.models.get(modelOwner, modelName);
console.log(modelData);
```

Response:
![image_2024-05-13_18-22-07](https://github.com/replicate/replicate-javascript/assets/25393145/3dd66488-3617-42c2-95c0-959aa74e405a)

**Comment by aron** [comment]
Hi @Alkons that's the `default_example`. Each model provides a set of example prompts so users can see how they work. We include the first of these in the model metadata ([docs](https://replicate.com/docs/reference/http#models.get)).

https://replicate.com/mistralai/mistral-7b-instruct-v0.2/examples

**Comment by Alkons** [comment]
> Hi @Alkons that's the `default_example`. Each model provides a set of example prompts so users can see how they work. We include the first of these in the model metadata ([docs](https://replicate.com/docs/reference/http#models.get)).
> 
> https://replicate.com/mistralai/mistral-7b-instruct-v0.2/examples

Maybe it makes sense to rename logs to the examples just to avoid such confusion.

**Comment by aron** [comment]
Thanks for the feedback! I'll share it with the team.
