### ISSUE TITLE
API responds 422 when input contains string[]

### ISSUE THREAD

**Issue by KeThang-V** [replicate/replicate-javascript#265]
Hi,

When I send an array of string in a parameter of the `input` of a new prediction I'm getting a code 422 (Unprocessable Entity) from the API. The error is `input.style_images: Invalid type. Expected: array, given: string`.

So I tried to find out why and found this by adding a console.log directly to the request in the replicate lib:
My original input sent to `replicate.predictions.create`:
```
{
  "input": {
    "style_images": ["string1", "string2"]
  },
  ...
}
```
The API request body sent from the lib is transformed like this:
```
{
  "body": {
    "source": '{"input":{"style_images":"string2"},...}',
    ...
  }
}
```

I also tried to make the same request with curl or replicate-python and it works.

Thank you

**Comment by mattt** [comment]
Hi @KeThang-V. Can you please share a link to the model you're running and the full code you tried for JS / Python / curl?

**Comment by KeThang-V** [comment]
The link to our private model: https://replicate.com/scenario-labs/style-transfer

JS code:
```
import Replicate  from 'replicate';

export async function runReplicate(props) {
  const replicate = new Replicate({
    auth: "***",
  });

  return replicate.predictions.create({
    model: "scenario-labs/style-transfer",
    version: "96fec4bad5f8231d89b4b7b5721cb66f8a76858b0469b909d5f21e42538e136e",
    input: {
    },
    webhook: 'https://***',
    webhook_events_filter: [,
  });

**Comment by KeThang-V** [comment]
@mattt Thanks for this, it works very well! 🔥

**Comment by guivr** [comment]
This is now failing again
