### ISSUE TITLE
replicate.files is undefined

### ISSUE THREAD

**Issue by treeder** [replicate/replicate-javascript#277]
Tried to upload a file, but getting `replicate.files` is undefined.

Just `console.log(replicate.files)` to reproduce.

**Comment by mattt** [comment]
Hi @treeder. What version of the library are you using? The files API was first added in [v0.30.0](https://github.com/replicate/replicate-javascript/releases/tag/v0.30.0).

**Comment by treeder** [comment]
I'm using `0.30.2`

**Comment by mattt** [comment]
Ah, I see what happened. Thanks for pointing this out. Got a fix in https://github.com/replicate/replicate-javascript/pull/278.

**Comment by mattt** [comment]
Thanks again for opening an issue about this @treeder. This should now be fixed in [v0.31.0](https://github.com/replicate/replicate-javascript/releases/tag/v0.31.0)

**Comment by treeder** [comment]
Awesome, thanks for the quick fix!
