### ISSUE TITLE
ApiError: Request to https://api.replicate.com/v1/files failed with status 413 Request Entity Too Large

### ISSUE THREAD

**Issue by flexchar** [replicate/replicate-javascript#286]
Trying to consume Whisper API with an audio file passed as a Blob to input. I receive `ApiError: Request to https://api.replicate.com/v1/files failed with status 413 Request Entity Too Large: <html>...`.

My audio file is 215MB. 

I won't include the code example as this seems to be undocumented API limitation. I also couldn't find any docs on file size limit beyond a few brief mentions on the feature in README. 

> File handle inputs are automatically uploaded to Replicate. See [replicate.files.create](https://github.com/replicate/replicate-javascript?tab=readme-ov-file#replicatefilescreate) for more information.

Is this something that could be raised? :)

In regards to this model/client using the most recent version as of today, July 5th 2024: https://replicate.com/turian/insanely-fast-whisper-with-video/api

**Comment by mattt** [comment]
Hi @flexchar. Sorry for the inconvenience there. You're correct that there's currently an undocumented upload limit of 100MiB. This will be documented with #287. 

We're working to raise that limit in the future. But for now, our guidance is to upload larger files to your own storage provider and pass a public URL as an input.
