### ISSUE TITLE
Not assignable to parameter of type '`${string}/${string}:${string}`

### ISSUE THREAD

**Issue by royherma** [replicate/replicate-javascript#304]
I'm trying to use the latest Flux Schnell in my Node.js backend via the API.

But in the documentation, there is no version or additional identifier after the colon. This causes me to get an error as below.

Argument of type '"black-forest-labs/flux-schnell"' is not assignable to parameter of type '`${string}/${string}:${string}`

When I try running it without the colon, I also get an error that the entity cannot be processed.

Any ideas about how to fix this? It does look like I have the latest npm version which is replicate 0.32

<img width="1376" alt="Screenshot 2024-09-09 at 7 24 48" src="https://github.com/user-attachments/assets/0b6f1af1-362c-4eaf-bae9-609fad1bf222">

**Comment by royherma** [comment]
@mattt mine looks a bit different..

    run(
      identifier: `${string}/${string}:${string}`,
      options: {
        input: object;
        wait?: boolean | { interval?: number; maxAttempts?: number };
        webhook?: string;
        webhook_events_filter?: WebhookEventType[];
      }
    ): Promise<object>;
    
   and see image as well:
   
   
<img width="951" alt="Screenshot 2024-09-10 at 7 59 05" src="https://github.com/user-attachments/assets/f261be9b-e75b-4d84-91c7-f5e459580669">

node.js
"replicate": "^0.32.1",

any ideas?

**Comment by royherma** [comment]
nvm - fixed! It does look like I had an older version that was just a mismatch in what my package said and what was actually installed. 

I uninstalled it - and then reinstalled to the latest version and it now worked.

However, it looks like this update is causing some issues with my firebase node backend.

@mattt Does this latest version of replicate not work on Node 14?

**Comment by mattt** [comment]
@royherma Node 18 is the minimum supported version for the Replicate library. I'd recommend upgrading from Node 14.

**Comment by royherma** [comment]
For sure, thank you. We can close this :) @mattt
