### ISSUE TITLE
Getting readable stream object from riffusion model instead of a https url

### ISSUE THREAD

**Issue by abubakarakram167** [replicate/replicate-javascript#320]
"Per the documentation for the Riffusion model, I was expecting to receive a direct HTTPS URL from Replicate's server for an audio file. However, I am encountering an unusual issue where I am receiving a readable stream object instead. Attached below is an image illustrating this.

I am currently utilizing the Node.js SDK in conjunction with Next.js 14. Any guidance or assistance on this matter would be greatly appreciated. Thank you!

MyCode Image is attached below:

![AbubakarsCode](https://github.com/user-attachments/assets/080734b6-76de-4b4f-b49b-6f6edd1fc70c)

**Comment by mikoaro** [comment]
Can you downgrade the package version to something like 0.34.0? This earlier release version worked for me. "replicate": "^0.34.0"

I had a similar error below with the latest version 1.0.0 just released.
"replicate": "^1.0.0"

//=> Code Snippet
```
const run = async () => {
  console.log("Running the model...");
  const output = await replicate.run(
    "bytedance/sdxl-lightning-4step:5599ed30703defd1d160a25a63321b4dec97101d98b4674bcc56e41f62f35637",
    {
      input: {
        prompt: "An astronaut riding a rainbow unicorn, cinematic, dramatic",
      },
    }
  );
  console.log(output);
};

run();
```

//=> Error
```
[
  ReadableStream { locked: false, state: 'readable', supportsBYOB: false }
]
```

**Comment by maxtotterman** [comment]
Stumeled upon the same issue while following examples from the documentation, but looking at the code: The default options is to send output as FileOutput, seen here:
https://github.com/replicate/replicate-javascript/blob/main/index.js#L63

You would need to pass in the input option: **useFileOutput: false**

**Comment by maxtotterman** [comment]
Hi!

Stumbeled upon same issue when trying to follow the documentation.
Checked the code, and in the 1.0.0 release: The default output is a stream.

See here:
https://github.com/replicate/replicate-javascript/blob/2b55fcb87a75f8417e942289c1b8c59d527077e1/index.js#L63

So you would need to instantiate Replicate with the option: useFileOutput:false.

Example
``` 
const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
  useFileOutput: false
});

```

**Comment by altezza04** [comment]
It seem the issue still present with **useFileOutput:false** 

```
import Replicate from "replicate";
const replicate = new Replicate({
  auth: process.env.REPLICATE_API_TOKEN,
  useFileOutput: false,
});

const model = "black-forest-labs/flux-schnell";
const input = {
  prompt: "a 19th century portrait of a raccoon gentleman wearing a suit",
};
const output = await replicate.run(model, { input });
console.log(output);
```

Output
`['data:application/octet-stream;base64,UklGRnJv...`

**Comment by aron** [comment]
@altezza04 you're seeing the expected behaviour here, you're getting back the string output rather than a `FileObject` instance. For flux-schnell and other fast models we're optimizing the delivery by inlining the responses as data-uris. The intention being that if you use the `FileObject` as a `ReadableStream` you as an author don't need to worry about the backing URL. It can be written to disk, streamed back to the browser or whatever else you need.

If you absolutely need the underlying url you can pass `wait: { mode: "poll" }` to the `run()` method to disable this behavior but I'd love to understand the use case.
