### ISSUE TITLE
need more accurate typing for v1

### ISSUE THREAD

**Issue by ZeroCho** [replicate/replicate-javascript#323]
Currently, the output type of replicate is `Promise<object>`, but real exact type is `Promise<FileOutput[]>` when useFileOutput is true, or `Promise<string[]>` when useFileOutput is false.

As the output type now is `Promise<object>`, I always have to cast type forcefully with `const output = await replicate.run(...) as unknown as FileOutput[]`

So I suggest updating type using generic like following codes.
```ts
  export default class Replicate<UseFileOutput = true> {
    constructor(options?: {
      auth?: string;
      userAgent?: string;
      baseUrl?: string;
      fetch?: (input: Request | string, init?: RequestInit) => Promise<Response>;
      fileEncodingStrategy?: FileEncodingStrategy;
      useFileOutput?: UseFileOutput;
    });

    run(
      identifier: `${string}/${string}` | `${string}/${string}:${string}`,
      options: {
        input: object;
        wait?: { mode: 'block'; interval?: number; timeout?: number } | { mode: 'poll'; interval?: number };
        webhook?: string;
        webhook_events_filter?: WebhookEventType[];
        signal?: AbortSignal;
      },
      progress?: (prediction: Prediction) => void,
    ): Promise<(UseFileOutput extends true ? FileOutput : string)[]>;
```
Changed parts are `<UseFileOutput = true>`, `useFileOutput?: UseFileOutput;`, and `Promise<(UseFileOutput extends true ? FileOutput : string)[]>;`

Those who useFileOutput as false can use replicate with type `Replicate<false>`.

**Comment by ZeroCho** [comment]
Oh, I found out that some models give me just `Promise<FileOutput>` instead of `Promise<FileOutput[]>`. The codes need to be changed.

```ts
  export default class Replicate<UseFileOutput = true> {
    constructor(options?: {
      auth?: string;
      userAgent?: string;
      baseUrl?: string;
      fetch?: (input: Request | string, init?: RequestInit) => Promise<Response>;
      fileEncodingStrategy?: FileEncodingStrategy;
      useFileOutput?: UseFileOutput;
    });

    run(
      identifier: `${string}/${string}` | `${string}/${string}:${string}`,
      options: {
        input: object;
        wait?: { mode: 'block'; interval?: number; timeout?: number } | { mode: 'poll'; interval?: number };
        webhook?: string;
        webhook_events_filter?: WebhookEventType[];
        signal?: AbortSignal;
      },
      progress?: (prediction: Prediction) => void,
    ): Promise<UseFileOutput extends true ? (FileOutput | FileOutput[]) : string[]>;
```

**Comment by aron** [comment]
Thanks for the feedback. We have some discussions about how to make the TypeScript annotations more integrated with the actual source code. We'll be sure to take this input on board. It's worth noting that output can be any shape that is [supported by cog](https://cog.run/python/#input-and-output-types).

**Comment by ZeroCho** [comment]
@aron Oh, I see. Does string represent [cog.Secret](https://cog.run/python/#secret)?

**Comment by aron** [comment]
Yes, `cog.Secret` is essentially a string input but we ensure that the contents is redacted throughout our system. We don't currently support those for outputs.

The `FileOutput` has an optimization, whereby if the model supports it and the file is <5mb we'll inline the file into the response in order to optimize for speed in delivering the file. We've had mixed feedback on this behaviour though, for the moment it's possible to opt-out by passing `wait: false` to the `run()` function.
