### ISSUE TITLE
Can you remove punycode from the dependencies?

### ISSUE THREAD

**Issue by keesvandorp** [replicate/replicate-javascript#335]
https://github.com/replicate/replicate-javascript/blob/0b7c8ebd9adb30f84ab420d1288e2ce1dac349cf/package-lock.json#L4525

**Comment by evilstreak** [comment]
Punycode is a transitive dependency of eslint, which we use as part of our CI process.

**Comment by keesvandorp** [comment]
Do you have plans to change that? The version of the punycode module bundled in Node.js is being deprecated. In a future major version of Node.js this module will be removed. Users currently depending on the punycode module should switch to using the userland-provided [Punycode.js](https://github.com/bestiejs/punycode.js) module instead. https://nodejs.org/api/punycode.html

**Comment by evilstreak** [comment]
It's a transitive dependency, not a direct dependency. To remove it would require us to replace any package we use that has a dependency on it. We'll consider that at the point this is causing problems for folks, but not if it's just to stop a warning that's being emitted.

Is the dependency on the bundled punycode library causing a problem for your app?

**Comment by keesvandorp** [comment]
For now not, it's just the warning, but since it will be deprecated it though it might be smart for you to update your library. But if you're not using it directly then it is more a job for other package maintainers I believe.
