### ISSUE TITLE
I am getting axios.create is not a function Error 

### ISSUE THREAD

**Issue by WernerWildenboer** [replicate/replicate-javascript#39]
Maybe somebody else has seen this, hope somebody has some advice 

```
import Replicate from "replicate";

const replicateToken = process.env.REPLICATE_API_TOKEN || "";

const replicate = new Replicate({
  auth: replicateToken,
});

const imageToText = async (imageFile: File) => {
  const output = await replicate.run(
    "methexis-inc/img2prompt:50adaf2d3ad20a6f911a8a9e3ccf777b263b8596fbd2c8fc26e8888f8a0edbb5",
    {
      input: {
        image: imageFile,
      },
    }
  );
  return output;
};

export default imageToText;


```

I am using a freshly minted CRA application

**Comment by mattt** [comment]
@WernerWildenboer What version of the `replicate` package are you using? We just removed axios as a dependency yesterday with version 0.9.0.

**Comment by mattt** [comment]
@WernerWildenboer Sorry, I just noticed you're mentioning that this was for a CRA application. This library is for Node.js applications and doesn't currently support client-side JavaScript. If you want to build a website with the Replicate API, check out our guide for [building a website with Next.js](https://replicate.com/docs/get-started/nextjs).

**Comment by WernerWildenboer** [comment]
Ah I am with you; awesome. Thank you so so much!
