### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation

### ISSUE THREAD

**Issue by fappaz** [replicate/replicate-javascript#56]
I just created a brand new Next.js project that should integrate with `"replicate": "^0.11.0"`, but I keep getting this error when calling the `run` function.

```
TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
```

This is my function, as simple as it gets:

```js
import Replicate from "replicate";

export async function getOutput(input) {
  const replicate = new Replicate({ auth: process.env.REPLICATE_AUTH_KEY });

  // Tried these, neither worked
  // replicate.fetch = fetch;
  // replicate.fetch = global.fetch;
  // replicate.fetch = globalThis.fetch;
  
  return await replicate.run(process.env.REPLICATE_IDENTIFIER, { input });
}
```

Does it mean Replicate is supposed to be used server-side only (e.g.: Node.js) and can't be called from the browser?

---

Edit: I managed to make it work only on Node.js, but only if I set the `node-fetch` (note: must be [version 2](https://github.com/node-fetch/node-fetch/tree/2.x) if using CommonJS instead of ES modules) as the fetch option, otherwise I get a `ReferenceError: fetch is not defined`.

```js
import fetch from 'node-fetch';
import Replicate from "replicate";

export async function getOutput(input) {
  const replicate = new Replicate({
    auth: process.env.REPLICATE_AUTH_KEY,
    fetch: fetch,
  });
  
  return await replicate.run(process.env.REPLICATE_IDENTIFIER, { input });
}
```

Is there anything in the documentation that I might have missed that explains the right way to go about it?

Also, would appreciate it if you could have the `options.fetch` documented, as I only found out about it after reading the source code.

**Comment by mattt** [comment]
Hi @fappaz. Thanks for trying out Replicate. I'm sorry for any snags you hit using this library along the way.

> Does it mean Replicate is supposed to be used server-side only (e.g.: Node.js) and can't be called from the browser?

Yes, that's correct. If you want to build a web application that uses Replicate's API, you can use a framework like Next.js to proxy client requests. Check out our [getting started guide](https://replicate.com/docs/get-started/nextjs) for more information 

I updated the README to call this out more explicitly with #60.

> Also, would appreciate it if you could have the `options.fetch` documented, as I only found out about it after reading the source code.

Absolutely. I just added this with https://github.com/replicate/replicate-javascript/pull/59 and https://github.com/replicate/replicate-javascript/pull/60.

**Comment by sky-admin** [comment]
I run it in cloudflare worker, its also report error: `TypeError: Illegal invocation` 
does it a same error? isn't worker a server side env?

**Comment by sky-admin** [comment]
after reading [getting started guide](https://replicate.com/docs/get-started/nextjs)
i try call fetch manully and success, why the sdk report error?

**Comment by mukhtharcm** [comment]
> I run it in cloudflare worker, its also report error: `TypeError: Illegal invocation` does it a same error? isn't worker a server side env?

did you got any solution?

**Comment by sky-admin** [comment]
> > I run it in cloudflare worker, its also report error: `TypeError: Illegal invocation` does it a same error? isn't worker a server side env?
> 
> did you got any solution?

use http api
