### ISSUE TITLE
this.fetch is not a function

### ISSUE THREAD

**Issue by SleeplessOne1917** [replicate/replicate-javascript#69]
When trying to generate an image, I get this error:
```
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]: TypeError: this.fetch is not a function
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at Replicate.request (/home/insomnia/lemmy-art-bot/node_modules/.pnpm/replicate@0.11.1/node_modules/replicate/index.js:147:33)
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at Replicate.createPrediction (/home/insomnia/lemmy-art-bot/node_modules/.pnpm/replicate@0.11.1/node_modules/replicate/lib/pred>
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at Replicate.run (/home/insomnia/lemmy-art-bot/node_modules/.pnpm/replicate@0.11.1/node_modules/replicate/index.js:103:47)
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at generateArt (/home/insomnia/lemmy-art-bot/bot.ts:26:13)
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at Object.<anonymous> (/home/insomnia/lemmy-art-bot/bot.ts:83:29)
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at Generator.next (<anonymous>)
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at /home/insomnia/lemmy-art-bot/bot.ts:31:71
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at new Promise (<anonymous>)
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at __awaiter (/home/insomnia/lemmy-art-bot/bot.ts:27:12)
May 11 20:37:11 lemmygrad-art-bot pnpm[42126]:     at Object.mention [as handle] (/home/insomnia/lemmy-art-bot/bot.ts:78:20)
```

I have no idea why this is happening. I'm running on Node 18.16.0, so `fetch` should be defined. I also made sure that my API key is correct. Here is how I am using the library:
```typescript
const replicate = new Replicate({
  auth: API_KEY,
});

const generateArt = (prompt: string) =>
  replicate.run(
    'ai-forever/kandinsky-2:601eea49d49003e6ea75a11527209c4f510a93e2112c969d548fbb45b9c4f19f',
    {
      input: {
        prompt,
        width: 768,
        height: 768,
        batch_size: 3,
      },
    }
  );
```

I tried passing in an option for `fetch` to the constructor, but it didn't show up in the typescript types.

**Comment by SleeplessOne1917** [comment]
I just updated to 0.12.1 and used `cross-fetch` for the fetch option. It works now. Thank you!

**Comment by Rafazeon** [comment]
@SleeplessOne1917 how u solve this?

**Comment by mattt** [comment]
@Rafazeon The README has instructions about how to configure `fetch` here: https://github.com/replicate/replicate-javascript#constructor

> The client makes requests to Replicate's API using
> [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch).
> By default, the `globalThis.fetch` function is used,
> which is available on [Node.js 18](https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental) and later,
> as well as
> [Cloudflare Workers](https://developers.cloudflare.com/workers/runtime-apis/fetch/),
> [Vercel Edge Functions](https://vercel.com/docs/concepts/functions/edge-functions),
> and other environments.
> 
> On earlier versions of Node.js
> and other environments where global fetch isn't available,
> you can install a fetch function from an external package like
> [cross-fetch](https://www.npmjs.com/package/cross-fetch)
> and pass it to the `fetch` option in the constructor.
> 
> ```js
> import Replicate from "replicate";
> import fetch from "cross-fetch";
> 
> const replicate = new Replicate({
>   // get your token from https://replicate.com/account
>   auth: process.env.REPLICATE_API_TOKEN,
>   fetch: fetch,
> });
> ```
