### ISSUE TITLE
ai-forever/kandinsky-2 mix_images

### ISSUE THREAD

**Issue by georgi1980** [replicate/replicate-javascript#78]
Is it possible to use mix_images of ai-forever/kandinsky-2 with replicate-javascript, or only the parameters given in https://replicate.com/ai-forever/kandinsky-2 are allowed?

**Comment by mattt** [comment]
Hi @georgi1980. The available inputs for a given model on Replicate are documented in the API tab: https://replicate.com/ai-forever/kandinsky-2/api. That model doesn't have a `mix_images` parameter, so passing it either has no effect or will cause an error.
