### ISSUE TITLE
Negative Prompt

### ISSUE THREAD

**Issue by AlexStan0** [replicate/replicate-javascript#85]
``# Input "Negative Prompt" prediction creation

When running a prediction using the replicate-javascript library using the following code

```javascript
const output = await replicate.run(
  "alexstan0/stable-diffusion-4:187d2ae3532a4991def03d0abadfe2dab60f8f07e8fe1a9cd13be58300a5d878",
  {
    input: {
      prompt: "a photo of cjw"
    }
  }
);
```

How would I pass through a negative prompt as seen on the Demo page of the model interface on replicate.com?

**Comment by mattt** [comment]
Hi @AlexStan0. To specify a negative prompt, pass the `negative_prompt` to your input:

```javascript
const output = await replicate.run(
  "alexstan0/stable-diffusion-4:187d2ae3532a4991def03d0abadfe2dab60f8f07e8fe1a9cd13be58300a5d878",
  {
    input: {
      prompt: "a photo of cjw",
      negative_prompt: "blurry"
    }
  }
);
```
