### ISSUE TITLE
replicate_1.default is not a constructor

### ISSUE THREAD

**Issue by canbalkaya** [replicate/replicate-javascript#92]
When I run my replicate code like below, I get this error: replicate_1.default is not a constructor.

```
const options = {
    auth: process.env.REPLICATE_API_KEY
}
const replicate = new Replicate(options)
```

The code is a basic endpoint function that defines replicate object and returns a string.

I'm using Typescript.

Node.js version: 18.15.11

**Comment by mattt** [comment]
How are you importing the Replicate library?

**Comment by canbalkaya** [comment]
Sorry for the late reply.

Yes, it works.
