### ISSUE TITLE
How to catch replicate errors without crashing?

### ISSUE THREAD

**Issue by pqseags** [replicate/replicate-javascript#94]
I'm trying to call replicate from a node.js environment. If I have a malformed model input, the replicate SDK throws an error that crashes my server. I'm unable to catch the error and handle it. Here's my code:

```
 try {
        console.log("try")
        const output = await replicate.run(model, { modelInput })
  } catch (error) {
        console.log("catch")
  }
 console.log('after')
```
    
    
   Here's my logs with the error: 
```
  try
(node:15518) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/pseagren/Documents/TITLES/dev/backend/wallflower/api/wallflower-backend/node_modules/replicate/index.js:159
      throw new Error(`API request failed: ${response.statusText}`);
            ^

Error: API request failed: Unprocessable Entity
    at Replicate.request (/Users/pseagren/Documents/TITLES/dev/backend/wallflower/api/wallflower-backend/node_modules/replicate/index.js:159:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.7.0
```

Oddly, sometimes (but infrequently) my catch block actually catches the error, but usually it doesn't and the server crashes. Am I missing something?

**Comment by mattt** [comment]
Hi, @pqseags. Thanks for writing in. I'm sorry you're having trouble with this. 

Here are two suggestions:

1. The `run` method is a shorthand for creating a prediction and waiting for its result. It throws an error if the prediction fails. However, the longer form `predictions.create` method doesn't `throw`, and instead populates its `error` property. So one option would be to migrate to that method instead.
2. The issue could be that your `try`-`catch` block isn't correctly catching promise rejections. If the `run` method returns a promise that rejects, and that promise rejection isn't caught inside an `async` function, it could be causing your `catch` block not to execute.

If the code you shared is part of an `async` function, it should catch the error properly. But if it's not, then you'll need to declare the enclosing function as async or handle the promise with `.catch()`:

```js
replicate.run(model, { modelInput })
  .then(output => {
    console.log('after');
  })
  .catch(error => {
    console.log("catch");
  });
```

**Comment by pqseags** [comment]
Thanks for the response @mattt. Your first suggestion worked well, and we wanted to migrate to use webhooks anyway so that's perfect. 

Regarding the second suggestion however, the code is in an `async` function, and I ran into the same issue with `.catch()`. Perhaps the error is being thrown incorrectly in replicate's `run` method? From my understanding it should be `Promise.reject() `rather than `throw new Error`

**Comment by mattt** [comment]
@pqseags Thanks for the update. I'm glad to hear that you found a solution.

My understanding is that when an error is thrown inside an async function, it's automatically wrapped into a rejected `Promise`.

**Comment by mattt** [comment]
@pqseags Oh wait, I see why this is happening. The original code you posted seems to be calling `replicate.run` without an `await`. I think adding that should fix your issue.

**Comment by pqseags** [comment]
Hmm I'm not familiar enough to say for sure. Definitely odd that I was seeing inconsistent behavior as well. Either way I'm happy with the `predictions.create` solution - thanks for the help!
