### ISSUE TITLE
allow custom request headers to be specified

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-javascript#95]
We have some internal headers that affect how we route requests. It would be nice to be able to specify those somehow, either at request time, or when instantiating the client.

cc @anotherjesse @philandstuff

**Comment by mattt** [comment]
You can accomplish this by overriding the `fetch` property of the `Client` like so:

```js
client.fetch = (url, options) => {
  const headers = new Headers(options && options.headers);

  // Inject the custom header
  headers.append('X-Custom-Header', 'some value');

  return fetch(url, { ...options, headers });
}
```

I just created #96 to document this in the README.
